### ISSUE TITLE
System.Text.Encoding.Default Unhandled Exception

### ISSUE THREAD

**Issue by cdeeef** [waf/CSharpRepl#130] opened 2022-05-05 08:22 UTC
### Version

0.3.5

## Initial Problem
When I just try the following code in the REPL, it suddenly throw an unhandled Exception and exited.
``` csharp
System.Text.Encoding.Default()
```
The output is:
```
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.CodeAnalysis.Scripting.Hosting.ObjectFormatterHelpers.GetMemberValue(MemberInfo member, Object obj, Exception& exception)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.Visitor.FormatObjectMembersRecursive(List`1 result, Object obj, Boolean includeNonPublic, Int32& lengthLimit)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.Visitor.FormatObjectMembers(Builder result, Object obj, TypeInfo preProxyTypeInfo, Boolean includeNonPublic, Boolean inline)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.Visitor.FormatMembers(Builder result, Object obj, Object proxy, Boolean includeNonPublic, Boolean inlineMembers)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.Visitor.FormatObjectRecursive(Builder result, Object obj, Boolean isRoot, String& debuggerDisplayName)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.Visitor.FormatObject(Object obj)
   at Microsoft.CodeAnalysis.Scripting.Hosting.CommonObjectFormatter.FormatObject(Object obj, PrintOptions options)
   at Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.CSharpObjectFormatter.FormatObject(Object obj, PrintOptions options)
   at CSharpRepl.Services.Roslyn.PrettyPrinter.FormatObject(Object obj, Boolean displayDetails) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\PrettyPrinter.cs:line 36
   at CSharpRepl.Services.Roslyn.RoslynServices.PrettyPrintAsync(Object obj, Boolean displayDetails) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl.Services\Roslyn\RoslynServices.cs:line 104
   at CSharpRepl.ReadEvalPrintLoop.PrintAsync(RoslynServices roslyn, IConsole console, EvaluationResult result, Boolean displayDetails) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 112
   at CSharpRepl.ReadEvalPrintLoop.RunAsync(Configuration config) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\ReadEvalPrintLoop.cs:line 76
   at CSharpRepl.Program.Main(String[] args) in D:\a\CSharpRepl\CSharpRepl\CSharpRepl\Program.cs:line 47
   at CSharpRepl.Program.<Main>(String[] args)
[1]    12417 abort      csharprepl
```
**However, the device I am using is a Mac Book Pro M1 Pro running Monterey 12.3.1**
So, the `D:\` output really got me confused.

## Further Exploration
I also tried some code like following in the REPL:
```csharp
var test = System.Text.Encoding.Default; //OK
test // Exited with same unhandled exception
```
To figure out whether it is the problem of REPL, I tried code like this in the Rider IDE with a newly created Console App:
```csharp
Console.WriteLine(System.Text.Encoding.Default);
```
which runned smoothly with the output:
```
System.Text.UTF8Encoding+UTF8EncodingSealed
```

**So, I thought there may be something wrong with the REPL itself, but not the .Net .**

## Supplement Infomation
The dotnet SDK I'm using is:
```
.NET SDK (反映任何 global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

运行时环境:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

I am not sure what is going on, hope you could find it.
Thanks for your REPL, really help me a lot learing dotNet !

Have a nice day : )

**Comment by kindermannhubert** [comment] 2022-05-05 08:25
Thanks for reporting.
It's a duplicate of #79.

**Closed by kindermannhubert** 2022-05-05 08:25 UTC
Labels: bug

**Comment by cdeeef** [comment] 2022-05-05 08:27
Oh sorry, I didn't notice that

**Comment by waf** [comment] 2022-05-05 11:40
Yeah, this is annoying. It's ultimately a bug in the Roslyn formatter APIs, but I think it affects enough types that we'll need to catch this and do some sort of "best effort" formatting until we can get the underlying issue fixed. Thanks for reporting it @cdeeef, and thanks @kindermannhubert for triaging!
